
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const ADD_PROFILE = 'ADD_PROFILE';
export const ADD_PROFILE_ERR = 'ADD_PROFILE_ERR';
export const ADD_EMP_PROFILE = 'ADD_EMP_PROFILE';
export const ADD_EMP_PROFILE_ERR = 'ADD_EMP_PROFILE_ERR';

export const ADD_DASHBOARD = 'ADD_DASHBOARD';
export const ADD_RAISED = 'ADD_RAISED';
export const ERR_RAISED = 'ERR_RAISED';
export const ADD_PENDING = 'ADD_PENDING';
export const ERR_PENDING = 'ERR_PENDING';
export const ADD_RESOLVED = 'ADD_RESOLVED';
export const ERR_RESOLVED = 'ERR_RESOLVED';

export const ADD_RECEIVED = 'ADD_RECEIVED';
export const ERR_RECEIVED = 'ERR_RECEIVED';
export const ADD_EMP_RESOLVED = 'ADD_EMP_RESOLVED';
export const ERR_EMP_RESOLVED = 'ERR_EMP_RESOLVED';